import { getDemoPage } from "@/actions/demo";
import { notFound } from "next/navigation";

function sanitizeDemoHtml(html: string): string {
  // Demo pages are generated by the app, but still treat stored HTML as untrusted.
  // Allow the Tailwind CDN script the template includes; drop any other scripts.
  const allow = /<script\s+src="https:\/\/cdn\.tailwindcss\.com"\s*><\/script>/gi;
  const scripts = html.match(allow) ?? [];
  const withoutScripts = html.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, "");
  return scripts.join("\n") + "\n" + withoutScripts;
}

export default async function DemoViewPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const demo = await getDemoPage(slug);
  if (!demo) notFound();

  return (
    <div
      className="min-h-screen bg-white"
      dangerouslySetInnerHTML={{ __html: sanitizeDemoHtml(demo.htmlContent) }}
    />
  );
}
